sd_model: /path/to/sd-turbo
osediff_checkpoint: null

conch_bin: /path/to/conch_v1_5_pytorch_model.bin
uni_checkpoint: /path/to/UNI/pytorch_model.bin
gigapath_checkpoint: /path/to/prov-gigapath/pytorch_model.bin
hf_root: null
